# Generated by Django 4.2.10 on 2024-05-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
