# Generated by Django 4.2.10 on 2024-04-02 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('USER_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USER_APP.usermodel')),
            ],
            options={
                'db_table': 'website_review',
            },
        ),
    ]
