# Generated by Django 4.2.10 on 2024-04-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER_APP', '0002_websitereviewmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmodel',
            name='credit_card_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='cvv',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='payment_option',
            field=models.CharField(choices=[('creditcard', 'Credit Card'), ('gpay', 'Google Pay')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymentmodel',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
