# Generated by Django 4.2.10 on 2024-04-10 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AGENT_APP', '0004_offermodel'),
        ('USER_APP', '0004_selectedpackage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selectedpackage',
            old_name='hotel',
            new_name='hotel_id',
        ),
        migrations.RenameField(
            model_name='selectedpackage',
            old_name='package',
            new_name='package_id',
        ),
        migrations.AlterModelTable(
            name='selectedpackage',
            table='selected_package',
        ),
        migrations.CreateModel(
            name='WishlistModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGENT_APP.packagemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USER_APP.usermodel')),
            ],
            options={
                'db_table': 'wishlist',
                'unique_together': {('user', 'package')},
            },
        ),
    ]
