# Generated by Django 4.2.10 on 2024-04-15 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER_APP', '0005_rename_hotel_selectedpackage_hotel_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='payment_option',
        ),
    ]
