# Generated by Django 4.2.10 on 2024-04-15 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AGENT_APP', '0004_offermodel'),
        ('USER_APP', '0006_remove_paymentmodel_payment_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='package_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AGENT_APP.packagemodel'),
        ),
    ]
