# Generated by Django 4.2.10 on 2024-04-20 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AGENT_APP', '0005_hotelmodel_hotel_description'),
        ('USER_APP', '0007_bookingmodel_package_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='special_request',
        ),
        migrations.RemoveField(
            model_name='bookingmodel',
            name='status',
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='car_rental',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='package_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AGENT_APP.packagemodel'),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='payment_status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
