# Generated by Django 4.2.10 on 2024-04-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER_APP', '0008_remove_bookingmodel_special_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmodel',
            name='credit_card_number',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='cvv',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='paymentmodel',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='SelectedPackage',
        ),
    ]
