# Generated by Django 4.2.10 on 2024-04-20 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AGENT_APP', '0007_alter_activitiesmodel_activities_and_more'),
        ('USER_APP', '0009_remove_paymentmodel_credit_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='package_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGENT_APP.packagemodel'),
        ),
    ]
