# Generated by Django 4.2.10 on 2024-04-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER_APP', '0010_alter_bookingmodel_package_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='package_id',
        ),
    ]
