# Generated by Django 4.2.10 on 2024-04-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER_APP', '0012_bookingmodel_package_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='special_request',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
