# Generated by Django 4.2.10 on 2024-04-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER_APP', '0013_bookingmodel_special_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingmodel',
            name='special_request',
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='booking_status',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
