# Generated by Django 4.2.10 on 2024-03-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGENT_APP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagemodel',
            name='activities',
        ),
        migrations.AddField(
            model_name='activitiesmodel',
            name='activity_images',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='activitiesmodel',
            name='activities',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activitiesmodel',
            name='activity_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packagemodel',
            name='status',
            field=models.CharField(default='active', max_length=255),
        ),
        migrations.AlterModelTable(
            name='packagesplit',
            table='package_split',
        ),
    ]
