# Generated by Django 4.2.10 on 2024-04-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGENT_APP', '0002_remove_packagemodel_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimage',
            name='hotel_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
