# Generated by Django 4.2.10 on 2024-04-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGENT_APP', '0003_alter_hotelimage_hotel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferModel',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('status', models.CharField(default='active', max_length=255)),
                ('applicable_agents', models.ManyToManyField(to='AGENT_APP.agentmodel')),
                ('applicable_packages', models.ManyToManyField(related_name='offers', to='AGENT_APP.packagemodel')),
            ],
            options={
                'db_table': 'offers',
            },
        ),
    ]
