# Generated by Django 4.2.10 on 2024-04-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGENT_APP', '0004_offermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelmodel',
            name='hotel_description',
            field=models.TextField(null=True),
        ),
    ]
