# Generated by Django 4.2.10 on 2024-04-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGENT_APP', '0005_hotelmodel_hotel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagemodel',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
