# Generated by Django 4.2.10 on 2024-04-20 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AGENT_APP', '0006_packagemodel_is_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitiesmodel',
            name='activities',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packageimagesmodel',
            name='package_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='AGENT_APP.packagemodel'),
        ),
        migrations.AlterField(
            model_name='packagemodel',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
