# Generated by Django 4.2.10 on 2024-04-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AGENT_APP', '0007_alter_activitiesmodel_activities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimage',
            name='hotel_image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
